language: r
sudo: required
bioc_required: false
warnings_are_errors: true

env:
 global:
   - _R_CHECK_FORCE_SUGGESTS_=0
   - CRAN: http://cran.rstudio.com

r_packages:
  - RUnit
r_binary_packages:
  - XML
  - Rcpp
  - knitr
  - brew
  - inline
  - highlight
  - formatR
  - highr
  - markdown
  - rgl
r_github_packages:
  - rstudio/rmarkdown
  - hadley/testthat

notifications:
  email:
    on_success: change
    on_failure: change

